export default {
  dateFormat: "YYYY-MM-DD",
  requisitiondetails: {
    id: null,
    location: null,
    requested_by: null,
    approved_by: null,
    rs_number: "",
    date_requested: "",
    date_needed: "",
  },
  requisitiondetailsitems: [],
  requisitionedit: {
    id: null,
    location: null,
    location_label: null,
    requested_by: null,
    requested_by_label: null,
    requisition_request_items: [],
  },
  requisitioneditcolumns: [
    {
      name: "quantity",
      label: "Quantity",
      field: "quantity",
      align: "left",
    },
    {
      name: "unit",
      label: "Unit",
      field: "unit",
      align: "left",
    },
    {
      name: "description_label",
      label: "Description",
      field: "description_label",
      align: "left",
    },
    {
      name: "purpose",
      label: "Purpose",
      field: "purpose",
      align: "left",
    },
  ],
  requisitiondetailscolumns: [
    {
      name: "quantity",
      label: "Quantity",
      field: "quantity",
      align: "left",
    },
    {
      name: "unit",
      label: "Unit",
      field: "unit",
      align: "left",
    },
    {
      name: "description",
      label: "Description",
      field: (row) => row.description.name,
      align: "left",
    },
    {
      name: "purpose",
      label: "Purpose",
      field: "purpose",
      align: "left",
    },
  ],
  requisition_request: {
    id: 0,
    location: null,
    requested_by: null,
    approved_by: null,
    rs_number: "",
    date_requested: "",
    date_needed: "",
    requisition_request_items: [],
  },
  requisition_request_item: {
    id: 0,
    item_number: null,
    quantity: null,
    unit: "",
    description: "",
    description_label: "",
    purpose: "",
  },
  requestdetailsinput: [
    {
      name: "quantity",
      label: "Quantity",
      icon: "123",
      type: "input",
    },
    {
      name: "unit",
      label: "Unit",
      icon: "ad_units",
      type: "input",
    },
    {
      name: "description",
      label: "Description",
      icon: "search",
      type: "select",
    },
    {
      name: "purpose",
      label: "Purpose",
      icon: "sunny",
      type: "input",
    },
  ],
  listallitemstableloading: false,
  postrequisitionrequestitemloading: false,
  requisitionrequestdialog: false,
  requisitiondetailspagedialog: false,
  requisitiondetailsloadingpage: false,
  requisitionsearchrsnumberloading: false,
  requisitionapprovalloading: false,
  requisitiondisapprovalloading: false,
  tableindexrows: [],
  tableindexcolumns: [
    {
      name: "rs_number",
      label: "RS Number",
      field: "rs_number",
      align: "left",
    },
    {
      name: "location",
      label: "Location",
      field: (row) => row.location.name,
      align: "left",
    },
    {
      name: "requested_by",
      label: "Requested By",
      field: (row) => row.requested_by.name,
      align: "left",
    },
    {
      name: "date_requested",
      label: "Date Requested",
      field: "date_requested",
      align: "left",
    },
    {
      name: "date_needed",
      label: "Date Needed",
      field: "date_needed",
      align: "left",
    },
    {
      name: "status",
      label: "Status",
      field: "status",
      align: "left",
    },
  ],
  tablecreatecolumns: [
    {
      name: "item_number",
      label: "Item Number",
      field: "item_number",
      align: "left",
    },
    {
      name: "quantity",
      label: "Quantity",
      field: "quantity",
      align: "left",
    },
    {
      name: "unit",
      label: "Unit",
      field: "unit",
      align: "left",
    },
    {
      name: "description_label",
      label: "Description",
      field: "description_label",
      align: "left",
    },
    {
      name: "purpose",
      label: "Purpose",
      field: "purpose",
      align: "left",
    },
  ],
  tablecreaterows: [],
  createrequisitionrequest: {
    location: null,
    requested_by: null,
    approved_by: null,
    rs_number: "",
    date_requested: "",
    date_needed: "",
    requisition_request_items: [],
  },
  selected: [],
  rsnumbersearchresults: [],
  requisitionitemsresults: [],
  editable: true,
  requisitioneditdialog: false,
  requisitionaddeditdialog: false,
  deleterequisitionitemloading: false,
  itemselected: [],
  removerequisitionitemloading: false,
  updaterequisitioneditloading: false
};
