export default {
  dateFormat: "YYYY-MM-DD",
  requisitiondetails: {
    location: null,
    requested_by: null,
    approved_by: null,
    rs_number: "",
    date_requested: "",
    date_needed: "",
  },
  requisitiondetailsitems: [],
  requisition_request: {
    id: 0,
    location: null,
    requested_by: null,
    approved_by: null,
    rs_number: "",
    date_requested: "",
    date_needed: "",
    requisition_request_items: [],
  },
  requisition_request_item: {
    id: 0,
    item_number: null,
    quantity: null,
    unit: "",
    description: "",
    purpose: "",
  },
  requestdetailsinput: [
    {
      name: "quantity",
      label: "Quantity",
      icon: "",
      type: "input",
    },
    {
      name: "unit",
      label: "Unit",
      icon: "",
      type: "input",
    },
    {
      name: "description",
      label: "Description",
      icon: "",
      type: "input",
    },
    {
      name: "purpose",
      label: "Purpose",
      icon: "",
      type: "input",
    },
  ],
  listallitemstableloading: false,
  postrequisitionrequestitemloading: false,
  requisitionrequestdialog: false,
  requisitiondetailspagedialog: false,
  requisitiondetailsloadingpage: false,
  tableindexrows: [],
  tableindexcolumns: [
    {
      name: "location",
      label: "Location",
      field: row => row.location.name,
      align: "left",
    },
    {
      name: "requested_by",
      label: "Requested By",
      field: row => row.requested_by.name,
      align: "left",
    },
    // {
    //   name: "approved_by",
    //   label: "Approved By",
    //   field: row => row.approved_by.name,
    //   align: "left",
    // },
    {
      name: "rs_number",
      label: "RS Number",
      field: "rs_number",
      align: "left",
    },
    {
      name: "date_requested",
      label: "Date Requested",
      field: "date_requested",
      align: "left",
    },
    {
      name: "date_needed",
      label: "Date Needed",
      field: "date_needed",
      align: "left",
    },
    {
      name: "status",
      label: "Status",
      field: "status",
      align: "left"
    }
  ],
  tablecreatecolumns: [
    {
      name: "item_number",
      label: "Item Number",
      field: "item_number",
      align: "left",
    },
    {
      name: "quantity",
      label: "Quantity",
      field: "quantity",
      align: "left",
    },
    {
      name: "unit",
      label: "Unit",
      field: "unit",
      align: "left",
    },
    {
      name: "description",
      label: "Description",
      field: "description",
      align: "left",
    },
    {
      name: "purpose",
      label: "Purpose",
      field: "purpose",
      align: "left",
    },
  ],
  tablecreaterows: [],
  createrequisitionrequest: {
    location: null,
    requested_by: 3,
    approved_by: null,
    rs_number: "",
    date_requested: "",
    date_needed: "",
    requisition_request_items: [],
  },
};
