export default {
  dateFormat: "YYYY-MM-DD",
  tableindexcolumns: [
    {
      name: "date",
      label: "Date",
      field: "date",
      align: "left",
    },
    {
      name: "delivered_to",
      label: "Delivered To",
      field: "delivered_to",
      align: "left",
    },
    {
      name: "address",
      label: "Address",
      field: (row) => row.location.name,
      align: "left",
    },
    {
      name: "prepared_by",
      label: "Prepared By",
      field: (row) => row.prepared_by.name,
      align: "left",
    },
    {
      name: "delivered_by",
      label: "Delivered By",
      field: (row) => row.delivered_by.name,
      align: "left",
    },
  ],
  tableindexrows: [],
  tablecreatecolumns: [
    {
      name: "rs_number_label",
      label: "RS Number",
      field: "rs_number_label",
      align: "left",
    },
    {
      name: "quantity",
      label: "Quantity",
      field: "quantity",
      align: "left",
    },
    {
      name: "quantity_int",
      label: "Quantity Int",
      field: "quantity_int",
      align: "left",
    },
    {
      name: "description",
      label: "Description",
      field: "description",
      align: "left",
    },
  ],
  tablecreaterows: [],
  deliveryreceiptdetails: {
    id: null,
    date: null,
    delivered_to: null,
    received_date: null,
    address: null,
    delivered_by: null,
    noted_by: null,
    prepared_by: null,
    received_by: null,
  },
  deliveryreceiptdetailsitems: [],
  deliveryreceiptpayload: {
    date: null,
    delivered_to: null,
    received_date: null,
    address: null,
    delivered_by: null,
    noted_by: null,
    prepared_by: null,
    received_by: null,
    delivery_receipt_items: [],
  },
  delivery_receipt_item: {
    rs_number: null,
    rs_number_label: null,
    quantity: null,
    quantity_int: null,
    description: null,
  },
  listallitemstableloading: false,
  postdeliveryreceiptitemloading: false,
  deliveryreceiptdialog: false,
  deliveryreceiptdetailspagedialog: false,
  deliveryreceiptdetailsloadingpage: false,
  deliveryreceiptinput: [
    {
      name: "rs_number",
      label: "RS Number",
      icon: "",
      type: "select",
    },
    {
      name: "quantity",
      label: "Quantity",
      icon: "",
      type: "input",
    },
    {
      name: "quantity_int",
      label: "Quantity in Number",
      icon: "",
      type: "input",
    },
    {
      name: "description",
      label: "Description",
      icon: "",
      type: "input",
    },
  ],
};
