export default {
  dateFormat: "YYYY-MM-DD",
  tableindexcolumns: [
    {
      name: "date",
      label: "Date",
      field: "date",
      align: "left",
    },
    {
      name: "invoice_number",
      label: "Invoice Number",
      field: "invoice_number",
      align: "left",
    },
    {
      name: "address",
      label: "Address",
      field: (row) => row.address.name,
      align: "left",
    },
    {
      name: "prepared_by",
      label: "Prepared By",
      field: (row) => row.prepared_by.name,
      align: "left",
    },
    {
      name: "delivered_by",
      label: "Delivered By",
      field: (row) => row.delivered_by.name,
      align: "left",
    },
  ],
  tableindexrows: [],
  tablecreatecolumns: [
    {
      name: "rs_number_label",
      label: "RS Number",
      field: "rs_number_label",
      align: "left",
    },
    {
      name: "quantity",
      label: "Quantity",
      field: "quantity",
      align: "left",
    },
    {
      name: "description_label",
      label: "Description",
      field: "description_label",
      align: "left",
    },
    {
      name: "invoice_number",
      label: "Delivery Receipt/Invoice Number",
      field: "invoice_number",
      align: "left",
    },
    {
      name: "remarks",
      label: "Remarks",
      field: "remarks",
      align: "left",
    },
  ],
  tablecreaterows: [],
  deliveryreceiptdetails: {
    id: null,
    invoice_number: null,
    date: null,
    delivered_to: null,
    received_date: null,
    address: null,
    delivered_by: null,
    noted_by: null,
    prepared_by: null,
    received_by: null,
  },
  deliveryreceiptdetailsitems: [],
  deliveryreceiptpayload: {
    invoice_number: null,
    date: null,
    delivered_to: null,
    received_date: null,
    address: null,
    delivered_by: null,
    noted_by: null,
    prepared_by: null,
    received_by: null,
    delivery_receipt_items: [],
  },
  delivery_receipt_item: {
    rs_number: null,
    rs_number_label: null,
    quantity: 0,
    description: null,
    description_label: null,
    remarks: null
  },
  listallitemstableloading: false,
  postdeliveryreceiptitemloading: false,
  deliveryreceiptdialog: false,
  deliveryreceiptdetailspagedialog: false,
  deliveryreceiptdetailsloadingpage: false,
  deliveryreceiptaddquantityremarksdialog: false,
  deliveryreceiptinput: [
    {
      name: "rs_number",
      label: "RS Number",
      icon: "",
      type: "select",
    },
    {
      name: "quantity",
      label: "Quantity",
      icon: "",
      type: "input",
    },
    {
      name: "description",
      label: "Description",
      icon: "",
      type: "input",
    },
  ],
  deliveryreceiptdetailscolumns: [
    {
      name: "rs_number",
      label: "RS Number",
      field: (row) => row.rs_number.rs_number,
      align: "left",
    },
    {
      name: "quantity",
      label: "Quantity",
      field: "quantity",
      align: "left",
    },
    {
      name: "description",
      label: "Description",
      field: (row) => row.description.name,
      align: "left",
    },
    {
      name: "remarks",
      label: "Remarks",
      field: "remarks",
      align: "left",
    },
  ],
  selected: [],
  deliveryreceiptsearchcolumns: [
    {
      name: "date_requested",
      label: "Date Requested",
      field: "date_requested",
      align: "left",
    },
    {
      name: "rs_number_label",
      label: "RS Number",
      field: "rs_number_label",
      align: "left",
    },
    {
      name: "description_label",
      label: "Description",
      field: "description_label",
      align: "left",
    },
    {
      name: "quantity_requested",
      label: "Quantity Requested",
      field: "quantity_requested",
      align: "left",
    },
    {
      name: "quantity_delivered",
      label: "Quantity Delivered",
      field: "quantity_delivered",
      align: "left",
    },
    {
      name: "requested_by",
      label: "Requested By",
      field: "requested_by",
      align: "left",
    },
    {
      name: "date_needed",
      label: "Date Needed",
      field: "date_needed",
      align: "left",
    },
    {
      name: "received_date",
      label: "Received Date",
      field: "received_date",
      align: "left",
    },
    {
      name: "invoice_number",
      label: "Invoice Number",
      field: "invoice_number",
      align: "left",
    },
    {
      name: "remarks",
      label: "Remarks",
      field: "remarks",
      align: "left",
    }
  ],
  deliveryreceiptsearchrows: [],
  deliveryreceiptsearchtableloading: false
};
