export default {
  dateFormat: "YYYY-MM-DD",
  tableindexcolumns: [
    {
      name: "gp_number",
      label: "GP Number",
      field: "gp_number",
      align: "left",
    },
    {
      name: "please_allow",
      label: "Visitor",
      field: "please_allow",
      align: "left",
    },
    {
      name: "purpose",
      label: "Purpose",
      field: "purpose",
      align: "left",
    },
    {
      name: "location",
      label: "Location",
      field: "location",
      align: "left",
    },
    {
      name: "date_time_in",
      label: "Date IN",
      field: "date_time_in",
      align: "left",
    },
    {
      name: "remarks",
      label: "Remarks",
      field: "remarks",
      align: "left",
    },
  ],
  tableindexrows: [],
  gatepassdetails: {
    gp_number: "",
    please_allow: "",
    date: "",
    purpose: "",
    prepared_by: "",
    noted_by: "",
    checked_by: "",
    location: "",
    date_time_in: "",
    date_time_out: "",
    remarks: "",
    gatepassdetailsitems: [],
  },
  gatepassdetailsitems: {
    item: "",
    description: "",
    quantity: 0,
  },
  tableindexloading: false,
  gatepassadditemloading: false,
  gatepassadditemdialog: false,
  gatepassremoveitemloading: false,
  gatepasspostitemloading: false,
  selected: [],
  createtablecolumn: [
    {
      name: "item",
      label: "Item",
      field: "item",
      align: "left",
    },
    {
      name: "description",
      label: "Item Description",
      field: "description",
      align: "left",
    },
    { name: "remarks", label: "Remarks", field: "remarks", align: "left" },
  ],
  createtablerows: [],
  gatepasscreateitem: {
    gp_number: "",
    please_allow: "",
    date: "",
    purpose: "",
    prepared_by: null,
    noted_by: null,
    checked_by: null,
    location: null,
    date_time_in: "",
    date_time_out: "",
    remarks: "",
    gatepasscreateitems: []
  },
  gatepasscreateitems: {
    item: "",
    description: null,
    quantity: 0,
  }
};
